"""initial_schema

Revision ID: 9e89289057a4
Revises: 
Create Date: 2026-06-19 19:58:43.934328
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '9e89289057a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_resource', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.alter_column('coupons', 'discount_value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('coupons', 'min_purchase_kes',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('coupons', 'max_discount_kes',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_index('ix_disputes_status_created', 'disputes', ['status', 'created_at'], unique=False)
    op.create_index('ix_disputes_subject', 'disputes', ['subject_type', 'subject_id'], unique=False)
    op.drop_index('idx_documents_property', table_name='documents')
    op.drop_index('idx_documents_type', table_name='documents')
    op.drop_index('idx_documents_uploader', table_name='documents')
    op.create_index(op.f('ix_documents_is_deleted'), 'documents', ['is_deleted'], unique=False)
    op.add_column('escrow_transactions', sa.Column('release_condition_met', sa.Boolean(), nullable=True))
    op.create_index('ix_escrow_status_created', 'escrow_transactions', ['status', 'created_at'], unique=False)
    op.add_column('fraud_reports', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_fraud_reports_status_created', 'fraud_reports', ['status', 'created_at'], unique=False)
    op.alter_column('leases', 'monthly_rent_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('leases', 'deposit_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_index('idx_leases_tenant', table_name='leases')
    op.drop_index('idx_leases_unit', table_name='leases')
    op.alter_column('maintenance_requests', 'estimated_cost_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('maintenance_requests', 'actual_cost_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_index('idx_maintenance_status', table_name='maintenance_requests')
    op.drop_index('idx_maintenance_unit', table_name='maintenance_requests')
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index('idx_payments_checkout', table_name='payments')
    op.drop_index('idx_payments_created', table_name='payments')
    op.drop_index('idx_payments_purpose', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_user', table_name='payments')
    op.alter_column('properties', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index('idx_properties_bedrooms', table_name='properties')
    op.drop_index('idx_properties_city', table_name='properties')
    op.drop_index('idx_properties_city_trgm', table_name='properties', postgresql_using='gin')
    op.drop_index('idx_properties_county', table_name='properties')
    op.drop_index('idx_properties_county_trgm', table_name='properties', postgresql_using='gin')
    op.drop_index('idx_properties_created', table_name='properties')
    op.drop_index('idx_properties_fts', table_name='properties', postgresql_using='gin')
    op.drop_index('idx_properties_listing_type', table_name='properties')
    op.drop_index('idx_properties_owner_created', table_name='properties')
    op.drop_index('idx_properties_owner_status', table_name='properties')
    op.drop_index('idx_properties_price', table_name='properties')
    op.drop_index('idx_properties_status', table_name='properties')
    op.drop_index('idx_properties_status_city', table_name='properties')
    op.drop_index('idx_properties_status_featured_created', table_name='properties')
    op.drop_index('idx_properties_trust', table_name='properties')
    op.drop_index('idx_properties_type', table_name='properties')
    op.drop_index('idx_properties_type_status', table_name='properties')
    op.drop_index('idx_properties_verified', table_name='properties')
    op.create_index(op.f('ix_properties_is_deleted'), 'properties', ['is_deleted'], unique=False)
    op.alter_column('referral_rewards', 'amount_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index('idx_referral_rewards_ref', table_name='referral_rewards')
    op.alter_column('referrals', 'rewards_earned',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('referrals', 'total_rewards',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_index('idx_referrals_referred', table_name='referrals')
    op.drop_index('idx_referrals_referrer', table_name='referrals')
    op.alter_column('rent_payments', 'amount_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('rent_payments', 'amount_paid_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('rent_payments', 'late_fee_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_index('idx_rent_payments_month', table_name='rent_payments')
    op.drop_index('idx_rent_payments_status', table_name='rent_payments')
    op.drop_index('idx_rent_payments_tenant', table_name='rent_payments')
    op.alter_column('rent_receipts', 'amount_kes',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.add_column('rental_units', sa.Column('county', sa.String(length=100), nullable=False))
    op.alter_column('rental_units', 'monthly_rent_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('rental_units', 'deposit_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_index('idx_rental_units_landlord', table_name='rental_units')
    op.create_index('ix_reviews_subject_created', 'reviews', ['subject_id', 'created_at'], unique=False)
    op.alter_column('subscriptions', 'amount_kes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index('idx_subscriptions_period_end', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_tier', table_name='subscriptions')
    op.drop_index('idx_subscriptions_user', table_name='subscriptions')
    op.drop_index('idx_tenants_phone', table_name='tenants')
    op.drop_index('idx_tenants_unit', table_name='tenants')
    op.drop_index('idx_title_chain_hash', table_name='title_chain_blocks')
    op.drop_index('idx_title_chain_property', table_name='title_chain_blocks')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index('idx_users_active', table_name='users')
    op.drop_index('idx_users_created', table_name='users')
    op.drop_index('idx_users_email_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('idx_users_name_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_verifications_property', table_name='verifications')
    op.drop_index('idx_verifications_requester', table_name='verifications')
    op.drop_index('idx_verifications_status', table_name='verifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_verifications_status', 'verifications', ['status'], unique=False)
    op.create_index('idx_verifications_requester', 'verifications', ['requester_id'], unique=False)
    op.create_index('idx_verifications_property', 'verifications', ['property_id'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_name_trgm', 'users', ['full_name'], unique=False, postgresql_using='gin')
    op.create_index('idx_users_email_trgm', 'users', ['email'], unique=False, postgresql_using='gin')
    op.create_index('idx_users_created', 'users', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index('idx_title_chain_property', 'title_chain_blocks', ['property_id', 'block_index'], unique=False)
    op.create_index('idx_title_chain_hash', 'title_chain_blocks', ['block_hash'], unique=False)
    op.create_index('idx_tenants_unit', 'tenants', ['unit_id'], unique=False)
    op.create_index('idx_tenants_phone', 'tenants', ['phone'], unique=False)
    op.create_index('idx_subscriptions_user', 'subscriptions', ['user_id'], unique=False)
    op.create_index('idx_subscriptions_tier', 'subscriptions', ['tier'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_period_end', 'subscriptions', ['current_period_end'], unique=False)
    op.alter_column('subscriptions', 'amount_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index('ix_reviews_subject_created', table_name='reviews')
    op.create_index('idx_rental_units_landlord', 'rental_units', ['landlord_id'], unique=False)
    op.alter_column('rental_units', 'deposit_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('rental_units', 'monthly_rent_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('rental_units', 'county')
    op.alter_column('rent_receipts', 'amount_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.create_index('idx_rent_payments_tenant', 'rent_payments', ['tenant_id'], unique=False)
    op.create_index('idx_rent_payments_status', 'rent_payments', ['status'], unique=False)
    op.create_index('idx_rent_payments_month', 'rent_payments', ['month'], unique=False)
    op.alter_column('rent_payments', 'late_fee_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('rent_payments', 'amount_paid_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('rent_payments', 'amount_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.create_index('idx_referrals_referrer', 'referrals', ['referrer_id'], unique=False)
    op.create_index('idx_referrals_referred', 'referrals', ['referred_user_id'], unique=False)
    op.alter_column('referrals', 'total_rewards',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('referrals', 'rewards_earned',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.create_index('idx_referral_rewards_ref', 'referral_rewards', ['referrer_id'], unique=False)
    op.alter_column('referral_rewards', 'amount_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index(op.f('ix_properties_is_deleted'), table_name='properties')
    op.create_index('idx_properties_verified', 'properties', ['is_verified'], unique=False)
    op.create_index('idx_properties_type_status', 'properties', ['property_type', 'status'], unique=False)
    op.create_index('idx_properties_type', 'properties', ['property_type'], unique=False)
    op.create_index('idx_properties_trust', 'properties', ['trust_score'], unique=False)
    op.create_index('idx_properties_status_featured_created', 'properties', ['status', sa.text('is_featured DESC'), sa.text('created_at DESC')], unique=False)
    op.create_index('idx_properties_status_city', 'properties', ['status', 'city'], unique=False)
    op.create_index('idx_properties_status', 'properties', ['status'], unique=False)
    op.create_index('idx_properties_price', 'properties', ['price'], unique=False)
    op.create_index('idx_properties_owner_status', 'properties', ['owner_id', 'status'], unique=False)
    op.create_index('idx_properties_owner_created', 'properties', ['owner_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_properties_listing_type', 'properties', ['listing_type'], unique=False)
    op.create_index('idx_properties_fts', 'properties', [sa.text("to_tsvector('english'::regconfig, (((((((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(description, ''::text)) || ' '::text) || COALESCE(address, ''::character varying)::text) || ' '::text) || COALESCE(city, ''::character varying)::text) || ' '::text) || COALESCE(county, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_properties_created', 'properties', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_properties_county_trgm', 'properties', ['county'], unique=False, postgresql_using='gin')
    op.create_index('idx_properties_county', 'properties', ['county'], unique=False)
    op.create_index('idx_properties_city_trgm', 'properties', ['city'], unique=False, postgresql_using='gin')
    op.create_index('idx_properties_city', 'properties', ['city'], unique=False)
    op.create_index('idx_properties_bedrooms', 'properties', ['bedrooms'], unique=False)
    op.alter_column('properties', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.create_index('idx_payments_user', 'payments', ['user_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_purpose', 'payments', ['purpose'], unique=False)
    op.create_index('idx_payments_created', 'payments', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_payments_checkout', 'payments', ['mpesa_checkout_request_id'], unique=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.create_index('idx_maintenance_unit', 'maintenance_requests', ['unit_id'], unique=False)
    op.create_index('idx_maintenance_status', 'maintenance_requests', ['status'], unique=False)
    op.alter_column('maintenance_requests', 'actual_cost_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('maintenance_requests', 'estimated_cost_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.create_index('idx_leases_unit', 'leases', ['unit_id'], unique=False)
    op.create_index('idx_leases_tenant', 'leases', ['tenant_id'], unique=False)
    op.alter_column('leases', 'deposit_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('leases', 'monthly_rent_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index('ix_fraud_reports_status_created', table_name='fraud_reports')
    op.drop_column('fraud_reports', 'reviewed_at')
    op.drop_index('ix_escrow_status_created', table_name='escrow_transactions')
    op.drop_column('escrow_transactions', 'release_condition_met')
    op.drop_index(op.f('ix_documents_is_deleted'), table_name='documents')
    op.create_index('idx_documents_uploader', 'documents', ['uploader_id'], unique=False)
    op.create_index('idx_documents_type', 'documents', ['document_type'], unique=False)
    op.create_index('idx_documents_property', 'documents', ['property_id'], unique=False)
    op.drop_index('ix_disputes_subject', table_name='disputes')
    op.drop_index('ix_disputes_status_created', table_name='disputes')
    op.alter_column('coupons', 'max_discount_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('coupons', 'min_purchase_kes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('coupons', 'discount_value',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_logs_created', 'audit_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
